### ISSUE TITLE
Having a faster render when using techdraw + freestyle

### ISSUE THREAD

**Issue by beraldoleal** [Laurent26/techdraw#3]
Hi @Laurent26 , one quick question:

Since we are just interested on the outline / hidden lines and not concerned about light passes how can we improve the render time? (I don't have a GPU, just a very modest CPU, if you would like to emulate this, just disable your GPU and enable two cores during render).

Is there any way to improve this? Also, maybe I need to better understand freestyle, but some strange lines are showing and I'm not getting a good result. (Maybe because of the bevel edges)

Here is my model.

[file.zip](https://github.com/Laurent26/techdraw/files/6448009/file.zip)

**Comment by beraldoleal** [comment]
About the strange lines, I'm talking about those diagonal lines, that I can see on my model:

![print](https://user-images.githubusercontent.com/49336/117580114-b287e700-b0cc-11eb-8166-92dd973de6fc.png)

**Comment by Laurent26** [comment]
Hi beraldoleal,

For the rendering speed, I exclusively use EEVEE render engine and not CYCLE. With your file, the rendering with CYCLE: 2 min 50s, with EEVEE: 9s.

For strange lines, you can play on some parameters of the Freestyles. I made a small example to show you. Note that Blender is not an industrial software of the parametric type, so you have to do some handling to get a correct rendering.

![1](https://user-images.githubusercontent.com/52755307/117582911-a91a7100-b104-11eb-9464-23a884ec2736.png)

![2](https://user-images.githubusercontent.com/52755307/117582916-b0417f00-b104-11eb-91a5-2514ca0fcead.png)

For this result, selected the lines you want to see then in the Edge menu used the Mark Freestyle Edge. Also check Edge Mark in the Freestyle properties. 
![3](https://user-images.githubusercontent.com/52755307/117582922-b6376000-b104-11eb-91f5-d192d3a9d056.png)

**Comment by beraldoleal** [comment]
Thank you, so much, @Laurent26!! Not expecting a reply on a Sunday. ;)

It helped a lot, I'm hitting some walls here, but eventually I will be able to render something useful.
