### ISSUE TITLE
Does not work for version 3.30

### ISSUE THREAD

**Issue by linc01** [Laurent26/techdraw#6]
Doesn't work on version 3.33, always reports a python type error in the "update settings".`techview.py, line551, expected an int type, not float`

**Comment by sulkka** [comment]
Modified lines 553 to 556 like this and got rid of the above mentioned error message.

            if (xdim - ydim) >= 0:
                bpy.context.scene.render.resolution_y = int(resolX * (ydim/xdim))
            if (xdim - ydim) < 0:
                bpy.context.scene.render.resolution_y = int(resolX * (ydim/xdim))

**Comment by linc01** [comment]
@sulkka Thanks!
